-- CreateTable
CREATE TABLE "Player" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "min" INTEGER NOT NULL,
    "sec" INTEGER NOT NULL,
    "ms" INTEGER NOT NULL
);
